name: publish-collector-agent

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}/collector-agent
  TAG_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  collector-agent: # reference from https://docs.docker.com/build/ci/github-actions/multi-platform/
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        with:
          submodules: "true"          
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v7
          push: true
          context: collector-agent
          tags: ${{ env.REGISTRY_IMAGE }}:${{ env.TAG_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  Release-Collector-agent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows]
        goarch: [amd64]
    steps:
    - name: Show environment
      run: export
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1
      id: release-ca
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: "https://dl.google.com/go/go1.18.10.linux-amd64.tar.gz"
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "collector-agent"
        binary_name: "collector-agent"
        extra_files: LICENSE collector-agent/CHANGES.md 
        ldflags: -X "github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/server.Version=${{ env.TAG_NAME }}"